import CommentModel from './CommentModel'




const comments: CommentModel[]=[
  new CommentModel(1,1,"坤行者",$r("app.media.user001"),"太秀了","3-12","北京省",109),
  new CommentModel(2,1,"行者坤",$r("app.media.user002"),"谢谢UP主，差点渴死的时候刷到了。非常好的视频","3-15","湖北省",112),
  new CommentModel(3,1,"小文大师兄",$r("app.media.user003"),"有用有用，收藏收藏","3-16","湖南省",11),
  new CommentModel(4,1,"小楚楚呀",$r("app.media.user004"),"这样容易打嗝！","3-16","北京省",513),
  new CommentModel(5,1,"彩色计数菌",$r("app.media.user005"),"加油","3-16","北京省",11),
  new CommentModel(6,1,"青春理塘少年不会爱上芙蓉佬王源",$r("app.media.user006"),"不会呼吸不会吞咽，完蛋了","3-16","湖北省",401),
  new CommentModel(7,1,"生活索然无味",$r("app.media.user007"),"我是突然不会正确吞咽了，每次喝水吃饭都很费劲，有什么解决方法吗","3-18","湖北省",11),
  new CommentModel(8,1,"榔子支持原味",$r("app.media.user008"),"做不到正确的吞咽法，有没有什么正确的练习方法？","3-18","河北省",127),
  new CommentModel(9,1,"我也不想做混子",$r("app.media.user009"),"这一期太专业了，一般人谁会知道啊","3-18","江苏省",222),
  new CommentModel(10,1,"自明_",$r("app.media.user010"),"非常非常难受，不习惯","3-22","湖北省",23),
  new CommentModel(11,1,"苏苏SSS1",$r("app.media.user011"),"封面有毒","3-22","湖北省",90),
  new CommentModel(12,1,"小许只爱打游戏",$r("app.media.user012"),"我以为吞口水呢。。。","4-12","江苏省",25),
  new CommentModel(13,1,"这饭你不吃也得吃",$r("app.media.user013"),"原来我连吞咽都不会...(||o_o)","4-12","湖北省",9),
  new CommentModel(7,1,"生活索然无味",$r("app.media.user007"),"我是突然不会正确吞咽了，每次喝水吃饭都很费劲，有什么解决方法吗","3-18","湖北省",11),
  new CommentModel(8,1,"榔子支持原味",$r("app.media.user008"),"做不到正确的吞咽法，有没有什么正确的练习方法？","3-18","河北省",127),
  new CommentModel(9,1,"我也不想做混子",$r("app.media.user009"),"这一期太专业了，一般人谁会知道啊","3-18","江苏省",222),


  new CommentModel(7,2,"生活索然无味",$r("app.media.user007"),"我是突然不会正确吞咽了，每次喝水吃饭都很费劲，有什么解决方法吗","3-18","湖北省",11),
  new CommentModel(1,2,"坤行者",$r("app.media.user001"),"太秀了","3-12","北京省",109),
  new CommentModel(2,2,"行者坤",$r("app.media.user002"),"谢谢UP主，差点渴死的时候刷到了。非常好的视频","3-15","湖北省",112),
  new CommentModel(3,2,"小文大师兄",$r("app.media.user003"),"有用有用，收藏收藏","3-16","湖南省",11),
  new CommentModel(4,2,"小楚楚呀",$r("app.media.user004"),"这样容易打嗝！","3-16","北京省",513),
  new CommentModel(5,2,"彩色计数菌",$r("app.media.user005"),"加油","3-16","北京省",11),
  new CommentModel(6,2,"青春理塘少年不会爱上芙蓉佬王源",$r("app.media.user006"),"不会呼吸不会吞咽，完蛋了","3-16","湖北省",401),
  new CommentModel(8,2,"榔子支持原味",$r("app.media.user008"),"做不到正确的吞咽法，有没有什么正确的练习方法？","3-18","河北省",127),
  new CommentModel(9,2,"我也不想做混子",$r("app.media.user009"),"这一期太专业了，一般人谁会知道啊","3-18","江苏省",222),
  new CommentModel(10,2,"自明_",$r("app.media.user010"),"非常非常难受，不习惯","3-22","湖北省",23),
  new CommentModel(11,2,"苏苏SSS1",$r("app.media.user011"),"封面有毒","3-22","湖北省",90),
  new CommentModel(12,2,"小许只爱打游戏",$r("app.media.user012"),"我以为吞口水呢。。。","4-12","江苏省",25),
  new CommentModel(13,2,"这饭你不吃也得吃",$r("app.media.user013"),"原来我连吞咽都不会...(||o_o)","4-12","湖北省",9),
  new CommentModel(8,2,"榔子支持原味",$r("app.media.user008"),"做不到正确的吞咽法，有没有什么正确的练习方法？","3-18","河北省",127),
  new CommentModel(9,2,"我也不想做混子",$r("app.media.user009"),"这一期太专业了，一般人谁会知道啊","3-18","江苏省",222),
  new CommentModel(10,2,"自明_",$r("app.media.user010"),"非常非常难受，不习惯","3-22","湖北省",23),
  new CommentModel(11,2,"苏苏SSS1",$r("app.media.user011"),"封面有毒","3-22","湖北省",90),

  new CommentModel(7,3,"生活索然无味",$r("app.media.user007"),"我是突然不会正确吞咽了，每次喝水吃饭都很费劲，有什么解决方法吗","3-18","湖北省",11),
  new CommentModel(8,3,"榔子支持原味",$r("app.media.user008"),"做不到正确的吞咽法，有没有什么正确的练习方法？","3-18","河北省",127),
  new CommentModel(9,3,"我也不想做混子",$r("app.media.user009"),"这一期太专业了，一般人谁会知道啊","3-18","江苏省",222),
  new CommentModel(10,3,"自明_",$r("app.media.user010"),"非常非常难受，不习惯","3-22","湖北省",23),
  new CommentModel(5,3,"彩色计数菌",$r("app.media.user005"),"加油","3-16","北京省",11),
  new CommentModel(1,3,"坤行者",$r("app.media.user001"),"太秀了","3-12","北京省",109),
  new CommentModel(2,3,"行者坤",$r("app.media.user002"),"谢谢UP主，差点渴死的时候刷到了。非常好的视频","3-15","湖北省",112),
  new CommentModel(10,3,"自明_",$r("app.media.user010"),"非常非常难受，不习惯","3-22","湖北省",23),
  new CommentModel(5,3,"彩色计数菌",$r("app.media.user005"),"加油","3-16","北京省",11),
  new CommentModel(3,3,"小文大师兄",$r("app.media.user003"),"有用有用，收藏收藏","3-16","湖南省",11),
  new CommentModel(4,3,"小楚楚呀",$r("app.media.user004"),"这样容易打嗝！","3-16","北京省",513),
  new CommentModel(6,3,"青春理塘少年不会爱上芙蓉佬王源",$r("app.media.user006"),"不会呼吸不会吞咽，完蛋了","3-16","湖北省",401),
  new CommentModel(11,3,"苏苏SSS1",$r("app.media.user011"),"封面有毒","3-22","湖北省",90),
  new CommentModel(12,3,"小许只爱打游戏",$r("app.media.user012"),"我以为吞口水呢。。。","4-12","江苏省",25),
  new CommentModel(13,3,"这饭你不吃也得吃",$r("app.media.user013"),"原来我连吞咽都不会...(||o_o)","4-12","湖北省",9),

  new CommentModel(1,4,"坤行者",$r("app.media.user001"),"太秀了","3-12","北京省",109),
  new CommentModel(2,4,"行者坤",$r("app.media.user002"),"谢谢UP主，差点渴死的时候刷到了。非常好的视频","3-15","湖北省",112),
  new CommentModel(3,4,"小文大师兄",$r("app.media.user003"),"有用有用，收藏收藏","3-16","湖南省",11),
  new CommentModel(4,4,"小楚楚呀",$r("app.media.user004"),"这样容易打嗝！","3-16","北京省",513),
  new CommentModel(5,4,"彩色计数菌",$r("app.media.user005"),"加油","3-16","北京省",11),
  new CommentModel(6,4,"青春理塘少年不会爱上芙蓉佬王源",$r("app.media.user006"),"不会呼吸不会吞咽，完蛋了","3-16","湖北省",401),
  new CommentModel(7,4,"生活索然无味",$r("app.media.user007"),"我是突然不会正确吞咽了，每次喝水吃饭都很费劲，有什么解决方法吗","3-18","湖北省",11),
  new CommentModel(8,4,"榔子支持原味",$r("app.media.user008"),"做不到正确的吞咽法，有没有什么正确的练习方法？","3-18","河北省",127),
  new CommentModel(9,4,"我也不想做混子",$r("app.media.user009"),"这一期太专业了，一般人谁会知道啊","3-18","江苏省",222),
  new CommentModel(10,4,"自明_",$r("app.media.user010"),"非常非常难受，不习惯","3-22","湖北省",23),
  new CommentModel(11,4,"苏苏SSS1",$r("app.media.user011"),"封面有毒","3-22","湖北省",90),
  new CommentModel(12,4,"小许只爱打游戏",$r("app.media.user012"),"我以为吞口水呢。。。","4-12","江苏省",25),
  new CommentModel(13,4,"这饭你不吃也得吃",$r("app.media.user013"),"原来我连吞咽都不会...(||o_o)","4-12","湖北省",9),
  new CommentModel(5,4,"彩色计数菌",$r("app.media.user005"),"加油","3-16","北京省",11),
  new CommentModel(6,4,"青春理塘少年不会爱上芙蓉佬王源",$r("app.media.user006"),"不会呼吸不会吞咽，完蛋了","3-16","湖北省",401),
  new CommentModel(7,4,"生活索然无味",$r("app.media.user007"),"我是突然不会正确吞咽了，每次喝水吃饭都很费劲，有什么解决方法吗","3-18","湖北省",11),
  new CommentModel(8,4,"榔子支持原味",$r("app.media.user008"),"做不到正确的吞咽法，有没有什么正确的练习方法？","3-18","河北省",127),
  new CommentModel(9,4,"我也不想做混子",$r("app.media.user009"),"这一期太专业了，一般人谁会知道啊","3-18","江苏省",222),
  new CommentModel(10,4,"自明_",$r("app.media.user010"),"非常非常难受，不习惯","3-22","湖北省",23),

  new CommentModel(1,5,"坤行者",$r("app.media.user001"),"太秀了","3-12","北京省",109),
  new CommentModel(2,5,"行者坤",$r("app.media.user002"),"谢谢UP主，差点渴死的时候刷到了。非常好的视频","3-15","湖北省",112),
  new CommentModel(3,5,"小文大师兄",$r("app.media.user003"),"有用有用，收藏收藏","3-16","湖南省",11),
  new CommentModel(4,5,"小楚楚呀",$r("app.media.user004"),"这样容易打嗝！","3-16","北京省",513),
  new CommentModel(5,5,"彩色计数菌",$r("app.media.user005"),"加油","3-16","北京省",11),
  new CommentModel(6,5,"青春理塘少年不会爱上芙蓉佬王源",$r("app.media.user006"),"不会呼吸不会吞咽，完蛋了","3-16","湖北省",401),
  new CommentModel(7,5,"生活索然无味",$r("app.media.user007"),"我是突然不会正确吞咽了，每次喝水吃饭都很费劲，有什么解决方法吗","3-18","湖北省",11),
  new CommentModel(8,5,"榔子支持原味",$r("app.media.user008"),"做不到正确的吞咽法，有没有什么正确的练习方法？","3-18","河北省",127),
  new CommentModel(9,5,"我也不想做混子",$r("app.media.user009"),"这一期太专业了，一般人谁会知道啊","3-18","江苏省",222),
  new CommentModel(10,5,"自明_",$r("app.media.user010"),"非常非常难受，不习惯","3-22","湖北省",23),
  new CommentModel(11,5,"苏苏SSS1",$r("app.media.user011"),"封面有毒","3-22","湖北省",90),
  new CommentModel(12,5,"小许只爱打游戏",$r("app.media.user012"),"我以为吞口水呢。。。","4-12","江苏省",25),
  new CommentModel(13,5,"这饭你不吃也得吃",$r("app.media.user013"),"原来我连吞咽都不会...(||o_o)","4-12","湖北省",9),
  new CommentModel(4,5,"小楚楚呀",$r("app.media.user004"),"这样容易打嗝！","3-16","北京省",513),
  new CommentModel(5,5,"彩色计数菌",$r("app.media.user005"),"加油","3-16","北京省",11),
  new CommentModel(6,5,"青春理塘少年不会爱上芙蓉佬王源",$r("app.media.user006"),"不会呼吸不会吞咽，完蛋了","3-16","湖北省",401),
  new CommentModel(7,5,"生活索然无味",$r("app.media.user007"),"我是突然不会正确吞咽了，每次喝水吃饭都很费劲，有什么解决方法吗","3-18","湖北省",11),
  new CommentModel(8,5,"榔子支持原味",$r("app.media.user008"),"做不到正确的吞咽法，有没有什么正确的练习方法？","3-18","河北省",127),
  new CommentModel(9,5,"我也不想做混子",$r("app.media.user009"),"这一期太专业了，一般人谁会知道啊","3-18","江苏省",222),

  new CommentModel(1,6,"坤行者",$r("app.media.user001"),"太秀了","3-12","北京省",109),
  new CommentModel(2,6,"行者坤",$r("app.media.user002"),"谢谢UP主，差点渴死的时候刷到了。非常好的视频","3-15","湖北省",112),
  new CommentModel(3,6,"小文大师兄",$r("app.media.user003"),"有用有用，收藏收藏","3-16","湖南省",11),
  new CommentModel(4,6,"小楚楚呀",$r("app.media.user004"),"这样容易打嗝！","3-16","北京省",513),
  new CommentModel(5,6,"彩色计数菌",$r("app.media.user005"),"加油","3-16","北京省",11),
  new CommentModel(6,6,"青春理塘少年不会爱上芙蓉佬王源",$r("app.media.user006"),"不会呼吸不会吞咽，完蛋了","3-16","湖北省",401),
  new CommentModel(7,6,"生活索然无味",$r("app.media.user007"),"我是突然不会正确吞咽了，每次喝水吃饭都很费劲，有什么解决方法吗","3-18","湖北省",11),
  new CommentModel(8,6,"榔子支持原味",$r("app.media.user008"),"做不到正确的吞咽法，有没有什么正确的练习方法？","3-18","河北省",127),
  new CommentModel(9,6,"我也不想做混子",$r("app.media.user009"),"这一期太专业了，一般人谁会知道啊","3-18","江苏省",222),
  new CommentModel(2,6,"行者坤",$r("app.media.user002"),"谢谢UP主，差点渴死的时候刷到了。非常好的视频","3-15","湖北省",112),
  new CommentModel(3,6,"小文大师兄",$r("app.media.user003"),"有用有用，收藏收藏","3-16","湖南省",11),
  new CommentModel(4,6,"小楚楚呀",$r("app.media.user004"),"这样容易打嗝！","3-16","北京省",513),
  new CommentModel(5,6,"彩色计数菌",$r("app.media.user005"),"加油","3-16","北京省",11),
  new CommentModel(6,6,"青春理塘少年不会爱上芙蓉佬王源",$r("app.media.user006"),"不会呼吸不会吞咽，完蛋了","3-16","湖北省",401),
  new CommentModel(7,6,"生活索然无味",$r("app.media.user007"),"我是突然不会正确吞咽了，每次喝水吃饭都很费劲，有什么解决方法吗","3-18","湖北省",11),
  new CommentModel(8,6,"榔子支持原味",$r("app.media.user008"),"做不到正确的吞咽法，有没有什么正确的练习方法？","3-18","河北省",127),
  new CommentModel(9,6,"我也不想做混子",$r("app.media.user009"),"这一期太专业了，一般人谁会知道啊","3-18","江苏省",222),
  new CommentModel(10,6,"自明_",$r("app.media.user010"),"非常非常难受，不习惯","3-22","湖北省",23),
  new CommentModel(11,6,"苏苏SSS1",$r("app.media.user011"),"封面有毒","3-22","湖北省",90),
  new CommentModel(12,6,"小许只爱打游戏",$r("app.media.user012"),"我以为吞口水呢。。。","4-12","江苏省",25),
  new CommentModel(13,6,"这饭你不吃也得吃",$r("app.media.user013"),"原来我连吞咽都不会...(||o_o)","4-12","湖北省",9),

  new CommentModel(1,7,"坤行者",$r("app.media.user001"),"太秀了","3-12","北京省",109),
  new CommentModel(2,7,"行者坤",$r("app.media.user002"),"谢谢UP主，差点渴死的时候刷到了。非常好的视频","3-15","湖北省",112),
  new CommentModel(3,7,"小文大师兄",$r("app.media.user003"),"有用有用，收藏收藏","3-16","湖南省",11),
  new CommentModel(4,7,"小楚楚呀",$r("app.media.user004"),"这样容易打嗝！","3-16","北京省",513),
  new CommentModel(5,7,"彩色计数菌",$r("app.media.user005"),"加油","3-16","北京省",11),
  new CommentModel(6,7,"青春理塘少年不会爱上芙蓉佬王源",$r("app.media.user006"),"不会呼吸不会吞咽，完蛋了","3-16","湖北省",401),
  new CommentModel(7,7,"生活索然无味",$r("app.media.user007"),"我是突然不会正确吞咽了，每次喝水吃饭都很费劲，有什么解决方法吗","3-18","湖北省",11),
  new CommentModel(8,7,"榔子支持原味",$r("app.media.user008"),"做不到正确的吞咽法，有没有什么正确的练习方法？","3-18","河北省",127),
  new CommentModel(9,7,"我也不想做混子",$r("app.media.user009"),"这一期太专业了，一般人谁会知道啊","3-18","江苏省",222),
  new CommentModel(10,7,"自明_",$r("app.media.user010"),"非常非常难受，不习惯","3-22","湖北省",23),
  new CommentModel(4,7,"小楚楚呀",$r("app.media.user004"),"这样容易打嗝！","3-16","北京省",513),
  new CommentModel(5,7,"彩色计数菌",$r("app.media.user005"),"加油","3-16","北京省",11),
  new CommentModel(6,7,"青春理塘少年不会爱上芙蓉佬王源",$r("app.media.user006"),"不会呼吸不会吞咽，完蛋了","3-16","湖北省",401),
  new CommentModel(7,7,"生活索然无味",$r("app.media.user007"),"我是突然不会正确吞咽了，每次喝水吃饭都很费劲，有什么解决方法吗","3-18","湖北省",11),
  new CommentModel(8,7,"榔子支持原味",$r("app.media.user008"),"做不到正确的吞咽法，有没有什么正确的练习方法？","3-18","河北省",127),
  new CommentModel(11,7,"苏苏SSS1",$r("app.media.user011"),"封面有毒","3-22","湖北省",90),
  new CommentModel(12,7,"小许只爱打游戏",$r("app.media.user012"),"我以为吞口水呢。。。","4-12","江苏省",25),
  new CommentModel(13,7,"这饭你不吃也得吃",$r("app.media.user013"),"原来我连吞咽都不会...(||o_o)","4-12","湖北省",9),
]


class CommentData{
    getByVideoId(videoId:number){
      let result: CommentModel[]=[]
      comments.map((item)=>{
        if(item.videoId==videoId){
            result.push(item)
        }
      })
      return result.length==0? null:result;
    }
}
let commentData = new CommentData()

export default commentData as CommentData





